version: '3'
services:
  db:
    image: mysql:8.0.34
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nestjs
    command: mysqld --sql_mode=""
  redis:
    image: redis:7.4.0
    ports:
      - 6379:6379
